site_name: HeXtractor
theme:
  name: material
  logo: assets/logo.png
  favicon: asserts/favicon.png

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid


nav:
  - Home: index.md
  - Concepts: concepts.md
  - Examples: examples.md
  - Contributing: contributing.md
  - API Reference:
      - Data Sources: reference/data_sources.md
      - Strustures: reference/structures.md
      - Extraction: reference/extraction.md
      - Integrations: reference/integrations.md
      - Visualization: reference/visualization.md
