name: Hextractor build and test

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



permissions:
  contents: read


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "poetry"
      - name: Install deps
        run: poetry install --with dev
      - name: Lint
        run: |
          poetry run ruff check
      - name: test
        run: |
          poetry run pytest -vv